# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(801, 366)
        Dialog.setMinimumSize(QtCore.QSize(741, 327))
        Dialog.setMaximumSize(QtCore.QSize(2000, 2000))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("logoibio.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setStyleSheet("QDialog{background-color:rgb(255, 255, 0);}")
        Dialog.setSizeGripEnabled(False)
        Dialog.setModal(False)
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(120, 110, 591, 231))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.btnCerrar = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnCerrar.setFont(font)
        self.btnCerrar.setStyleSheet("QPushButton{background-color:rgb(85, 255, 0);}\n"
"\n"
"QPushButton:hover{background-color:orange;}")
        self.btnCerrar.setObjectName("btnCerrar")
        self.gridLayout.addWidget(self.btnCerrar, 2, 0, 1, 1)
        self.btnInfo = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnInfo.setFont(font)
        self.btnInfo.setStyleSheet("QPushButton{background-color:rgb(85, 255, 0);}\n"
"\n"
"QPushButton:hover{background-color:orange;}")
        self.btnInfo.setObjectName("btnInfo")
        self.gridLayout.addWidget(self.btnInfo, 1, 0, 1, 1)
        self.btnInitEnsayo = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnInitEnsayo.setFont(font)
        self.btnInitEnsayo.setStyleSheet("QPushButton{background-color:rgb(85, 255, 0);}\n"
"\n"
"QPushButton:hover{background-color:orange;}")
        self.btnInitEnsayo.setObjectName("btnInitEnsayo")
        self.gridLayout.addWidget(self.btnInitEnsayo, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(280, 60, 271, 22))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.labelTBIO = QtWidgets.QLabel(Dialog)
        self.labelTBIO.setGeometry(QtCore.QRect(700, 20, 81, 91))
        self.labelTBIO.setText("")
        self.labelTBIO.setPixmap(QtGui.QPixmap("../ibioresized.png"))
        self.labelTBIO.setObjectName("labelTBIO")
        self.labelUTEC = QtWidgets.QLabel(Dialog)
        self.labelUTEC.setGeometry(QtCore.QRect(0, 0, 201, 121))
        self.labelUTEC.setText("")
        self.labelUTEC.setPixmap(QtGui.QPixmap("../output-onlinepngtools.png"))
        self.labelUTEC.setObjectName("labelUTEC")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 340, 221, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Cálculo de blindajes"))
        self.btnCerrar.setText(_translate("Dialog", "Cerrar"))
        self.btnInfo.setText(_translate("Dialog", "Información"))
        self.btnInitEnsayo.setText(_translate("Dialog", "Calculadora"))
        self.label.setText(_translate("Dialog", "Cálculo de blindajes rayos X"))
        self.label_2.setText(_translate("Dialog", "Versión 1.0: Actualizada 24/02/2022"))
